:toc:
:icons: font
:source-highlighter: prettify
:project_id: dependency-checker
:tabsize: 2

== 1. Technology stack

=== Core technologies

[source]
----
  - Framework  : Spring Boot (v2.7.2)
  - Build tool : Gradle (v.7.4.1)
  - Language   : Kotlin (v.1.6.21)
----

=== Spring Boot starters

[source]
----
  - API dev     : Spring Web
  - Website dev : Mustache
  - DB access   : Spring Data JPA
  - App metrics : Actuator
----

=== Other Spring dependencies

[source]
----
  - Spring Kafka
----

=== Database dependencies

[source]
----
  - Driver : H2 Database
----

== 2. Project build and boot

Since the build tool is gradle, standard build tasks are used. For build and unit testing, just run:

[source]
----
  $ ./gradlew build
----

For starting the system, just use standard Spring boot gradle tasks:

[source]
----
  $ ./gradlew bootRun
----

== 3. Project structure

=== Microservices
The project is divided in 3 main subsystems/microservices built on Spring Boot:

==== 1. REST API microservice
Source code for the REST API is in the https://github.com/macvaz/dependency-checker/tree/develop/src/main/kotlin/es/macvaz/spring/kotlin/dep_checker/api[api] package.

All API endpoints are placed under this preffix : http://localhost:8080/api/.

Currently, the only endpoints implemented are regarding 'IngestedFile' entity. One example is this service: http://localhost:8080/api/ingestedFile/

==== 2. Website microservice
Source code for the operational website is in the https://github.com/macvaz/dependency-checker/tree/develop/src/main/kotlin/es/macvaz/spring/kotlin/dep_checker/web[web] package.

The website microservice is exposed at: http://localhost:8080/

==== 3. Kafka consumer microservice

Source code for the Kafka consumer is in the https://github.com/macvaz/dependency-checker/tree/develop/src/main/kotlin/es/macvaz/spring/kotlin/dep_checker/kafka[kafka] package.

This microservice requires a kafka broker available in order to boot. A great introductory documentation for Apache Kafka is the https://kafka.apache.org/quickstart[official kickstart guide ].

In order to start a local kafka server, just follow the guide. Once installed,  start zookeeper and kafka servers:

[source]
----
  $ bin/zookeeper-server-start.sh config/zookeeper.properties
  $ bin/kafka-server-start.sh config/server.properties
----

=== Data model
All Spring Data source code (domain objects and data repositories) are placed in the https://github.com/macvaz/dependency-checker/tree/develop/src/main/kotlin/es/macvaz/spring/kotlin/dep_checker/model[model] package.

== 4. Future work

Dependencies not activated yet

[source]
----
  - DB Migrations: Liquibase
----
